#!/usr/bin/env python3
"""
LaunchForge CLI — the "5-minute new game" entry point (E13.2.5).

    # scaffold a brand-new game from a single prompt
    python cli.py init --name "Word Puzzle 01" --genre word \
        --platform android,ios --ads MAX --analytics Firebase,Adjust

This creates games/<slug>/ with:
    product.yaml          # game metadata + monetization + analytics + remote config
    monetization.yaml     # waterfall-by-geo (AI-editable in E13.3)
    release.yaml          # version / store / build profile
    gamefactory_config.json  # generated SDK runtime config (from product.yaml)

Then point your Unity project's Assets/Resources/GameFactory/gamefactory_config.json
at the generated json (or copy it). No per-game SDK wiring needed.
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "src"))


def _slug(name: str) -> str:
    s = name.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "game"


_PRODUCT_TMPL = """\
# Auto-generated by `launchforge init`. Edit values, then run config_generator.
product:
  name: "{name}"
  genre: "{genre}"
  platforms: [{platforms}]
  package_name: "com.yourcompany.{slug}"
  bundle_id: "com.yourcompany.{slug}"

monetization:
  provider: {ads}                 # MAX | LevelPlay  (mapped to SDK registry key)
  sdk_keys:
    android: "REPLACE_WITH_{ads}_APP_KEY"
    ios: "REPLACE_WITH_{ads}_APP_KEY"
  placements:
    rewarded: "REPLACE_WITH_REWARD_PLACEMENT"
    interstitial: "REPLACE_WITH_INTERSTITIAL_PLACEMENT"
    banner: "REPLACE_WITH_BANNER_PLACEMENT"
  optimize:
    auto_apply: false
    report_cron: "0 9 * * *"
    eCPM_floor_step: 0.02
    min_fill_rate: 0.05

analytics:
  providers: [{analytics}]
  firebase_key: "REPLACE_WITH_FIREBASE_KEY"
  adjust_token: "REPLACE_WITH_ADJUST_TOKEN"

remote_config:
  ads:
    reward_frequency: 3
    interstitial_gap: 2
  gameplay:
    level_difficulty: 1.1
    reward_multiplier: 2

iap_products: []
"""


def cmd_init(args):
    slug = _slug(args.name)
    game_dir = os.path.join(HERE, "games", slug)
    os.makedirs(game_dir, exist_ok=True)

    platforms = [p.strip() for p in args.platform.split(",") if p.strip()]
    analytics = [a.strip() for a in args.analytics.split(",") if a.strip()]
    ads = args.ads.strip()

    product_yaml = _PRODUCT_TMPL.format(
        name=args.name,
        genre=args.genre,
        slug=slug,
        platforms=", ".join(f'"{p}"' for p in platforms),
        ads=ads,
        analytics=", ".join(f'"{a}"' for a in analytics),
    )
    (open(os.path.join(game_dir, "product.yaml"), "w", encoding="utf-8").write(product_yaml))

    # copy monetization.yaml + release.yaml from the examples
    for fname in ("monetization.example.yaml", "release.example.yaml"):
        src = os.path.join(HERE, fname)
        if os.path.exists(src):
            dst = os.path.join(game_dir, fname.replace(".example", ""))
            open(dst, "w", encoding="utf-8").write(open(src, encoding="utf-8").read())

    # generate the SDK runtime config
    import yaml
    from config_generator import build_config
    cfg = yaml.safe_load(product_yaml)
    out = build_config(cfg)
    out_path = os.path.join(game_dir, "gamefactory_config.json")
    open(out_path, "w", encoding="utf-8").write(json.dumps(out, indent=2, ensure_ascii=False))

    print(f"[launchforge] created game '{args.name}' at games/{slug}/")
    for f in ("product.yaml", "monetization.yaml", "release.yaml", "gamefactory_config.json"):
        print(f"   - {f}")
    print("\nNext steps:")
    print(f"  1. Edit games/{slug}/product.yaml (package_name, app_key, placements, tokens)")
    print(f"  2. In Unity: GameFactory > Setup Project")
    print(f"  3. Copy games/{slug}/gamefactory_config.json ->")
    print(f"     YourProject/Assets/Resources/GameFactory/gamefactory_config.json")
    print(f"  4. Build & upload (launchforge/src/orchestrator.py --apply)")


def main():
    ap = argparse.ArgumentParser(description="LaunchForge CLI")
    sub = ap.add_subparsers(dest="cmd")

    p_init = sub.add_parser("init", help="Scaffold a new game project")
    p_init.add_argument("--name", required=True)
    p_init.add_argument("--genre", default="puzzle")
    p_init.add_argument("--platform", dest="platform", default="android,ios")
    p_init.add_argument("--ads", default="MAX")
    p_init.add_argument("--analytics", default="Firebase,Adjust")
    p_init.set_defaults(func=cmd_init)

    args = ap.parse_args()
    if not getattr(args, "cmd", None):
        ap.print_help()
        return
    args.func(args)


if __name__ == "__main__":
    main()
