using System;
using System.Collections.Generic;
using UnityEngine;

namespace GameFactory.Core
{
    /// <summary>
    /// Strongly-typed mirror of gamefactory_config.json (generated by LaunchForge config_generator.py
    /// and placed at Assets/Resources/GameFactory/gamefactory_config.json).
    /// One config file per game; the SDK reads it at runtime from Resources.
    /// </summary>
    [Serializable]
    public class GameFactoryConfig
    {
        public string game_name;
        public AdsConfig ads;
        public AnalyticsConfig analytics;
        public RemoteConfigData remote_config;
        public IapConfig iap;

        [Serializable]
        public class AdsConfig
        {
            // Standalone ad providers (native C# adapter in this SDK, selected by config key):
            //   "MAX"       -> AppLovin MAX mediation hub (recommended; mediates all networks below)
            //   "LevelPlay" -> ironSource LevelPlay mediation
            //   "AdMob"     -> Google AdMob standalone (Google Mobile Ads SDK)
            // Mediated networks (no per-network adapter; enabled in the MAX/LevelPlay dashboard and
            // imported as MAX adapter packages): AdMob, Meta, UnityAds, Vungle, Mintegral, Pangle,
            // AmazonAPS, InMobi, Chartboost. See AdChannelRegistry.EuUsChannels for the full roster.
            public string provider = "MAX";
            public string app_key;
            public string reward_id;
            public string interstitial_id;
            public string banner_id;
        }

        [Serializable]
        public class AnalyticsConfig
        {
            public List<string> providers = new List<string>(); // Firebase, Adjust
            public string firebase_key;
            public string adjust_token;
            // Optional event backend (E15.2.7). When non-empty, the SDK POSTs buffered
            // events to this HTTPS endpoint so player_monetization can ingest them.
            // Empty = disabled (Lean default: no network calls; events stay in offline cache).
            public string event_endpoint;
            // Stable app slug used to route events into data/player_events/<app_id>.jsonl
            // on the receiver. Falls back to game_name when empty. One SDK instance = one game,
            // so a single app_id covers every event in the buffer.
            public string app_id;
        }

        [Serializable]
        public class RemoteConfigData
        {
            // Dot-path flattened entry bag: {"ads.reward_frequency":"3","gameplay.level_difficulty":"1.1"}
            // Nested remote_config in product.yaml is flattened to this by config_generator.
            public List<RemoteEntry> entries = new List<RemoteEntry>();
        }

        [Serializable]
        public class RemoteEntry
        {
            public string key;
            public string value;
        }

        [Serializable]
        public class IapConfig
        {
            public bool enabled;
            // Product catalog (emitted by LaunchForge config_generator from product.yaml).
            // type: "consumable" | "non_consumable" | "subscription".
            public List<IapProduct> products = new List<IapProduct>();
        }

        [Serializable]
        public class IapProduct
        {
            public string id;
            public string type = "consumable";
        }

        /// <summary>Loads the per-project config copied by the Editor installer.</summary>
        public static GameFactoryConfig LoadFromResources()
        {
            var json = Resources.Load<TextAsset>("GameFactory/gamefactory_config");
            if (json == null) return null;
            try { return JsonUtility.FromJson<GameFactoryConfig>(json.text); }
            catch (Exception e)
            {
                Debug.LogError("[GameFactory] parse config failed: " + e.Message);
                return null;
            }
        }
    }
}
