"""Gallery Report — True Winner 画廊 HTML 报告

生成 true_winner_gallery.html: 缩略图画廊 + DNA 标注
"""
import json
from pathlib import Path
from typing import Dict, List, Optional

from ..config import OUTPUT_DIR, REPORTS_DIR, THUMBNAILS_DIR, ensure_dirs


GALLERY_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>True Winner Gallery - Performance Grounded Intelligence</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f0f23; color: #eee; padding: 20px; }}
h1 {{ text-align: center; margin: 20px 0; color: #fbbf24; }}
.subtitle {{ text-align: center; color: #888; margin-bottom: 30px; }}
.gallery {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 20px; padding: 20px; }}
.card {{ background: #1a1a2e; border-radius: 12px; overflow: hidden; transition: transform 0.2s; }}
.card:hover {{ transform: translateY(-4px); box-shadow: 0 8px 24px rgba(233,69,96,0.2); }}
.card-img {{ width: 100%; height: 200px; object-fit: cover; background: #16213e; }}
.card-body {{ padding: 15px; }}
.card-title {{ font-size: 14px; font-weight: 600; margin-bottom: 8px; color: #fbbf24; }}
.card-metrics {{ display: grid; grid-template-columns: 1fr 1fr; gap: 6px; margin-bottom: 10px; }}
.metric {{ font-size: 11px; }}
.metric .label {{ color: #888; }}
.metric .value {{ color: #4ade80; font-weight: 600; }}
.dna-tags {{ display: flex; flex-wrap: wrap; gap: 4px; }}
.tag {{ font-size: 10px; padding: 2px 8px; border-radius: 10px; background: #16213e; color: #60a5fa; border: 1px solid #333; }}
.tag.gameplay {{ background: #1e3a5f; color: #60a5fa; }}
.tag.reward {{ background: #3f1e1e; color: #f87171; }}
.tag.style {{ background: #1e3f2e; color: #4ade80; }}
.footer {{ text-align: center; margin: 40px 0; color: #666; font-size: 12px; }}
</style>
</head>
<body>
<h1>True Winner Gallery</h1>
<p class="subtitle">Top performing creatives with Vision DNA analysis | v2.1.8</p>

<div class="gallery">
{cards}
</div>

<div class="footer">
Generated by Performance Grounded Intelligence | {total} Winners Analyzed
</div>
</body>
</html>"""

CARD_TEMPLATE = """<div class="card">
<img class="card-img" src="{thumbnail_url}" alt="{title}" onerror="this.style.display='none'">
<div class="card-body">
<div class="card-title">{title}</div>
<div class="card-metrics">
<div class="metric"><span class="label">Spend</span><br><span class="value">${spend}</span></div>
<div class="metric"><span class="label">Revenue</span><br><span class="value">${revenue}</span></div>
<div class="metric"><span class="label">ROAS</span><br><span class="value">{roas}</span></div>
<div class="metric"><span class="label">CPI</span><br><span class="value">${cpi}</span></div>
</div>
<div class="dna-tags">
{tags}
</div>
</div>
</div>"""


class GalleryReport:
    """Winner 画廊报告生成器"""

    def generate(self, dna_data: Optional[Dict] = None) -> Path:
        """生成 true_winner_gallery.html

        Args:
            dna_data: true_winner_dna.json 数据
                      如果为 None 则从文件加载

        Returns:
            生成的 HTML 文件路径
        """
        ensure_dirs()

        if dna_data is None:
            dna_data = self._load_dna()

        winners = dna_data.get("winners", [])
        cards_html = []

        for winner in winners:
            perf = winner.get("performance", {})
            dna = winner.get("dna", {})

            # 缩略图
            thumb_url = ""
            if winner.get("thumbnail_urls"):
                thumb_url = winner["thumbnail_urls"][0]
            elif winner.get("source_ad_ids"):
                # 尝试本地文件
                for ad_id in winner["source_ad_ids"][:1]:
                    local = THUMBNAILS_DIR / f"{ad_id}.jpg"
                    if local.exists():
                        thumb_url = f"../thumbnails/{ad_id}.jpg"

            # 标题
            names = winner.get("sample_names", [])
            title = names[0] if names else winner.get("asset_id", "Unknown")
            if len(title) > 35:
                title = title[:32] + "..."

            # DNA 标签
            tags = []
            gameplay = dna.get("gameplay", {})
            if gameplay.get("type"):
                tags.append(f'<span class="tag gameplay">{gameplay["type"]}</span>')
            reward = dna.get("reward", {})
            if reward.get("type"):
                tags.append(f'<span class="tag reward">{reward["type"]}</span>')
            style = dna.get("style", {})
            if style.get("color_palette"):
                tags.append(f'<span class="tag style">{style["color_palette"]}</span>')
            if style.get("render_style"):
                tags.append(f'<span class="tag style">{style["render_style"]}</span>')
            layout = dna.get("layout", "")
            if layout:
                tags.append(f'<span class="tag">{layout}</span>')

            card = CARD_TEMPLATE.format(
                thumbnail_url=thumb_url,
                title=title,
                spend=f"{perf.get('spend', 0):,.0f}",
                revenue=f"{perf.get('all_revenue', 0):,.0f}",
                roas=f"{perf.get('iap_roas', 0):.1%}",
                cpi=f"{perf.get('cpi', 0):.1f}",
                tags="\n".join(tags),
            )
            cards_html.append(card)

        html = GALLERY_HTML_TEMPLATE.format(
            cards="\n".join(cards_html),
            total=len(winners),
        )

        output_path = REPORTS_DIR / "true_winner_gallery.html"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

        print(f"[GalleryReport] 已生成: {output_path} ({len(winners)} winners)")
        return output_path

    def _load_dna(self) -> Dict:
        """从文件加载 DNA 数据"""
        path = OUTPUT_DIR / "true_winner_dna.json"
        if path.exists():
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        return {"winners": []}
