"""Ranking Report — Winner 排名 HTML 报告

生成 winner_ranking.html: 交互式排名表
"""
import json
from pathlib import Path
from typing import Dict, List, Optional

from ..config import OUTPUT_DIR, REPORTS_DIR, ensure_dirs


RANKING_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Winner Ranking - Performance Grounded Intelligence</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #1a1a2e; color: #eee; padding: 20px; }}
h1 {{ text-align: center; margin: 20px 0; color: #e94560; }}
.stats {{ display: flex; gap: 20px; justify-content: center; margin: 20px 0; flex-wrap: wrap; }}
.stat-card {{ background: #16213e; padding: 15px 25px; border-radius: 10px; text-align: center; }}
.stat-card .value {{ font-size: 24px; font-weight: bold; color: #0f3460; }}
.stat-card .label {{ font-size: 12px; color: #aaa; margin-top: 5px; }}
.pool-section {{ margin: 30px 0; }}
.pool-title {{ font-size: 18px; margin: 15px 0; padding: 10px; background: #16213e; border-left: 4px solid #e94560; border-radius: 4px; }}
table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
th, td {{ padding: 10px 12px; text-align: left; border-bottom: 1px solid #333; }}
th {{ background: #16213e; color: #e94560; font-weight: 600; }}
tr:hover {{ background: #16213e44; }}
.rank {{ font-weight: bold; color: #e94560; }}
.roas {{ color: #4ade80; }}
.roas.low {{ color: #f87171; }}
.score-bar {{ display: inline-block; height: 8px; background: #e94560; border-radius: 4px; }}
.thumbnail {{ width: 50px; height: 50px; object-fit: cover; border-radius: 6px; }}
.footer {{ text-align: center; margin: 40px 0; color: #666; font-size: 12px; }}
</style>
</head>
<body>
<h1>Winner Ranking Report</h1>
<p style="text-align:center;color:#888;">Performance Grounded Intelligence v2.1.8</p>

<div class="stats">
{stats_cards}
</div>

{pool_sections}

<div class="footer">
Generated by Performance Grounded Intelligence | Data Period: {data_period}
</div>
</body>
</html>"""

STAT_CARD_TEMPLATE = '<div class="stat-card"><div class="value" style="color:{color}">{value}</div><div class="label">{label}</div></div>'

POOL_SECTION_TEMPLATE = """<div class="pool-section">
<div class="pool-title">{pool_name} ({count} winners)</div>
<table>
<thead><tr><th>#</th><th>Thumbnail</th><th>Ad Name</th><th>Spend</th><th>Revenue</th><th>ROAS</th><th>CPI</th><th>Score</th></tr></thead>
<tbody>
{rows}
</tbody>
</table>
</div>"""


class RankingReport:
    """Winner 排名报告生成器"""

    def generate(self, pools_data: Optional[Dict] = None) -> Path:
        """生成 winner_ranking.html

        Args:
            pools_data: 三池数据 (scale/efficiency/pattern)
                        如果为 None 则从文件加载

        Returns:
            生成的 HTML 文件路径
        """
        ensure_dirs()

        if pools_data is None:
            pools_data = self._load_pools()

        # 统计卡片
        total_winners = sum(len(v) for v in pools_data.values())
        total_spend = sum(
            w.get("spend", 0)
            for pool in pools_data.values()
            for w in pool
        )
        avg_roas = 0
        roas_values = [
            w.get("iap_roas", 0)
            for pool in pools_data.values()
            for w in pool
            if w.get("iap_roas", 0) > 0
        ]
        if roas_values:
            avg_roas = sum(roas_values) / len(roas_values)

        stats_cards = "\n".join([
            STAT_CARD_TEMPLATE.format(value=total_winners, label="Total Winners", color="#e94560"),
            STAT_CARD_TEMPLATE.format(value=f"${total_spend:,.0f}", label="Total Spend", color="#4ade80"),
            STAT_CARD_TEMPLATE.format(value=f"{avg_roas:.1%}", label="Avg ROAS", color="#60a5fa"),
            STAT_CARD_TEMPLATE.format(value=len(pools_data), label="Winner Pools", color="#fbbf24"),
        ])

        # 池子区块
        pool_names = {
            "scale": "Scale Winners (High Spend + Positive ROAS)",
            "efficiency": "Efficiency Winners (High ROAS)",
            "pattern": "Creative Pattern Winners (Top 10% Score)",
        }
        pool_sections = ""
        for pool_key, pool_label in pool_names.items():
            winners = pools_data.get(pool_key, [])
            if not winners:
                continue
            rows = self._build_rows(winners)
            pool_sections += POOL_SECTION_TEMPLATE.format(
                pool_name=pool_label,
                count=len(winners),
                rows=rows,
            )

        # 渲染
        html = RANKING_HTML_TEMPLATE.format(
            stats_cards=stats_cards,
            pool_sections=pool_sections,
            data_period="2024-11 ~ 2025-07",
        )

        output_path = REPORTS_DIR / "winner_ranking.html"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

        print(f"[RankingReport] 已生成: {output_path}")
        return output_path

    def _build_rows(self, winners: List[dict]) -> str:
        """构建表格行"""
        rows = []
        for i, w in enumerate(winners[:30], 1):  # 最多 30 行
            roas = w.get("iap_roas", 0)
            roas_class = "roas" if roas >= 0.5 else "roas low"
            thumb_url = ""
            if w.get("thumbnail_urls"):
                thumb_url = w["thumbnail_urls"][0]
            thumb_html = f'<img class="thumbnail" src="{thumb_url}" alt="">' if thumb_url else "-"

            names = w.get("sample_names", [])
            name = names[0] if names else w.get("asset_id", "?")
            if len(name) > 30:
                name = name[:27] + "..."

            score = w.get("winner_score", 0)
            score_width = int(score * 100)

            row = f"""<tr>
<td class="rank">{i}</td>
<td>{thumb_html}</td>
<td>{name}</td>
<td>${w.get('spend', 0):,.0f}</td>
<td>${w.get('all_revenue', 0):,.0f}</td>
<td class="{roas_class}">{roas:.1%}</td>
<td>${w.get('cpi', 0):.1f}</td>
<td><span class="score-bar" style="width:{score_width}px"></span> {score:.3f}</td>
</tr>"""
            rows.append(row)
        return "\n".join(rows)

    def _load_pools(self) -> Dict[str, List]:
        """从文件加载三池数据"""
        pools = {}
        pool_file_map = {
            "scale": "scale_winners.json",
            "efficiency": "efficiency_winners.json",
            "pattern": "creative_pattern_winners.json",
        }
        from ..config import WINNERS_DIR
        for name, filename in pool_file_map.items():
            path = WINNERS_DIR / filename
            if path.exists():
                with open(path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                pools[name] = data.get("top_20", [])
            else:
                pools[name] = []
        return pools
