"""
E16.6.13 — ASO Autonomous Operator: data models.

The final execution layer of the ASO Agent. Closes the entire E16.6 loop
from detection → planning → approval → execution → monitoring → learning.

Key concepts:
  * ``ASOOperationState`` — 9-stage state machine for one operation
  * ``ASOOperationPlan`` — unified action plan from any ASO module
  * ``ApprovalPolicy`` — 3-tier risk-based approval rules
  * ``ASOOperationExperience`` — recorded outcome for learning
  * ``ASOAutonomousReport`` — daily operator output
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


# --------------------------------------------------------------------------- #
# 1. Operation state machine
# --------------------------------------------------------------------------- #
class ASOOperationState(str, Enum):
    """Nine-stage lifecycle of one ASO operation."""
    DETECTED = "DETECTED"
    ANALYZING = "ANALYZING"
    PLANNED = "PLANNED"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    READY = "READY"
    EXECUTING = "EXECUTING"
    MEASURING = "MEASURING"
    COMPLETED = "COMPLETED"
    LEARNED = "LEARNED"


# --------------------------------------------------------------------------- #
# 2. Risk / approval levels
# --------------------------------------------------------------------------- #
class ApprovalLevel(str, Enum):
    """Three-tier execution permission."""
    AUTO = "AUTO"              # Level 1: fully automatic
    HUMAN_CONFIRM = "HUMAN_CONFIRM"  # Level 2: AI prepares, human approves
    HUMAN_DECIDE = "HUMAN_DECIDE"    # Level 3: human decision required


class RiskCategory(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


# --------------------------------------------------------------------------- #
# 3. Operation plan
# --------------------------------------------------------------------------- #
@dataclass
class ASOOperationPlan:
    """Unified operation plan generated by the planner."""

    plan_id: str
    game_id: str
    market: str
    action_type: str  # e.g. "UPDATE_SCREENSHOT", "KEYWORD_REFRESH"
    reason: str = ""
    expected_impact: float = 0.0
    confidence: float = 0.0
    risk_category: RiskCategory = RiskCategory.LOW
    required_assets: List[str] = field(default_factory=list)
    source_modules: List[str] = field(default_factory=list)
    state: ASOOperationState = ASOOperationState.DETECTED
    approval_level: ApprovalLevel = ApprovalLevel.AUTO
    task_id: str = ""
    created_at: str = field(default_factory=_now_iso)
    updated_at: str = field(default_factory=_now_iso)

    def advance(self, next_state: ASOOperationState) -> None:
        self.state = next_state
        self.updated_at = _now_iso()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "plan_id": self.plan_id,
            "game_id": self.game_id,
            "market": self.market,
            "action_type": self.action_type,
            "reason": self.reason,
            "expected_impact": round(self.expected_impact, 4),
            "confidence": round(self.confidence, 4),
            "risk_category": self.risk_category.value,
            "required_assets": self.required_assets,
            "source_modules": self.source_modules,
            "state": self.state.value,
            "approval_level": self.approval_level.value,
            "task_id": self.task_id,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


# --------------------------------------------------------------------------- #
# 4. Operation experience — recorded after completion
# --------------------------------------------------------------------------- #
@dataclass
class ASOOperationExperience:
    """Result of one completed ASO operation."""

    plan_id: str
    game_id: str
    market: str
    action_type: str
    before_metrics: Dict[str, float] = field(default_factory=dict)
    after_metrics: Dict[str, float] = field(default_factory=dict)
    reward: float = 0.0
    success: bool = False
    notes: str = ""
    created_at: str = field(default_factory=_now_iso)

    @property
    def cvr_change(self) -> float:
        b = self.before_metrics.get("cvr", 0.0)
        a = self.after_metrics.get("cvr", 0.0)
        return (a - b) / b if b > 0 else 0.0

    @property
    def revenue_change(self) -> float:
        b = self.before_metrics.get("revenue", 0.0)
        a = self.after_metrics.get("revenue", 0.0)
        return (a - b) / b if b > 0 else 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "plan_id": self.plan_id,
            "game_id": self.game_id,
            "market": self.market,
            "action_type": self.action_type,
            "before_metrics": self.before_metrics,
            "after_metrics": self.after_metrics,
            "reward": round(self.reward, 6),
            "success": self.success,
            "notes": self.notes,
            "created_at": self.created_at,
        }


# --------------------------------------------------------------------------- #
# 5. Daily report
# --------------------------------------------------------------------------- #
@dataclass
class ASOAutonomousReport:
    """Daily ASO autonomous operator output."""

    date: str
    games_scanned: int = 0
    opportunities_detected: int = 0
    plans_created: int = 0
    auto_executed: int = 0
    pending_approval: int = 0
    completed_today: int = 0
    patterns_learned: int = 0
    high_priority_plans: List[ASOOperationPlan] = field(default_factory=list)
    operations_summary: List[Dict[str, Any]] = field(default_factory=list)
    created_at: str = field(default_factory=_now_iso)

    def to_markdown(self) -> str:
        lines: List[str] = []
        lines.append(f"# ASO Autonomous Report")
        lines.append(f"")
        lines.append(f"**Date:** {self.date}")
        lines.append(f"**Portfolio Scan:** {self.games_scanned} games")
        lines.append(f"")
        lines.append(f"## Summary")
        lines.append(f"- **Opportunities Detected:** {self.opportunities_detected}")
        lines.append(f"- **Plans Created:** {self.plans_created}")
        lines.append(f"- **Auto-Executed:** {self.auto_executed}")
        lines.append(f"- **Pending Approval:** {self.pending_approval}")
        lines.append(f"- **Completed Today:** {self.completed_today}")
        lines.append(f"- **Patterns Learned:** {self.patterns_learned}")
        lines.append(f"")

        if self.high_priority_plans:
            lines.append(f"## High Priority Operations")
            for plan in self.high_priority_plans:
                appr = plan.approval_level.value
                lines.append(f"")
                lines.append(f"### {plan.game_id} ({plan.market})")
                lines.append(f"- **Action:** {plan.action_type}")
                lines.append(f"- **Reason:** {plan.reason}")
                lines.append(f"- **Confidence:** {plan.confidence:.0%}")
                lines.append(f"- **Approval:** {appr}")
                lines.append(f"- **Status:** {plan.state.value}")
                lines.append(f"")

        if self.operations_summary:
            lines.append(f"## Operations Summary")
            for op in self.operations_summary[:10]:
                status = op.get("state", "unknown")
                lines.append(
                    f"- **{op.get('game_id', '?')}** ({op.get('market', '?')}): "
                    f"{op.get('action_type', '?')} — {status}"
                )

        return "\n".join(lines)


__all__ = [
    "ASOOperationState",
    "ApprovalLevel",
    "RiskCategory",
    "ASOOperationPlan",
    "ASOOperationExperience",
    "ASOAutonomousReport",
]
