"""Feature Importance Report — 可解释因果报告生成器。

将 regressor 输出的特征重要性转化为业务语言的可解释报告。
输出两种格式：
  1. 结构化 JSON (用于下游系统)
  2. 可读 Markdown (用于团队阅读)
"""
from __future__ import annotations
from typing import List, Tuple


def generate_causal_report(
    target: str,
    top_drivers: List[Tuple[str, float]],
    negative_drivers: List[Tuple[str, float]],
    r2: float = None,
    n_samples: int = 0,
) -> dict:
    """生成结构化因果解释报告。

    Args:
        target: "roas" | "ctr" | "cvr"
        top_drivers: [(name, impact), ...]
        negative_drivers: [(name, impact), ...]
        r2: model R²
        n_samples: number of samples

    Returns:
        dict 包含自然语言解释 + 量化影响
    """
    if not top_drivers and not negative_drivers:
        return {
            "target": target,
            "verdict": f"Insufficient data to determine {target.upper()} drivers.",
        }

    top_name = top_drivers[0][0] if top_drivers else None
    top_impact = top_drivers[0][1] if top_drivers else 0
    neg_name = negative_drivers[0][0] if negative_drivers else None
    neg_impact = negative_drivers[0][1] if negative_drivers else 0

    # Build natural language explanation
    why_high = _generate_high_explanation(target, top_drivers[:3])
    why_low = _generate_low_explanation(target, negative_drivers[:3])
    action = _generate_action(top_drivers, negative_drivers, target)

    report = {
        "target": target.upper(),
        "model_r2": round(r2, 4) if r2 else None,
        "n_samples": n_samples,
        "causal_explanation": {
            "why_high_performance": {
                "root_cause": f"High {target.upper()} is driven by {top_name} (impact +{top_impact:.4f})" if top_name else "No significant positive drivers",
                "details": why_high,
            },
            "why_low_performance": {
                "root_cause": f"Low {target.upper()} is caused by {neg_name} (impact {neg_impact:.4f})" if neg_name else "No significant negative drivers",
                "details": why_low,
            },
            "recommended_action": action,
        },
        "impact_quantification": {
            "top_drivers": [
                {
                    "feature": n,
                    "impact": round(v, 4),
                    "impact_label": f"+{abs(v)*100:.0f}% per std" if v > 0 else f"-{abs(v)*100:.0f}% per std",
                    "direction": "positive" if v > 0 else "negative",
                }
                for n, v in (top_drivers + negative_drivers)
            ],
        },
    }

    return report


def generate_markdown_report(reports: List[dict]) -> str:
    """Generate human-readable markdown from structured reports."""
    lines = []
    lines.append("# 🧠 Visual Feature → Performance Causal Report")
    lines.append("")

    for r in reports:
        target = r.get("target", "?")
        lines.append(f"## 🎯 {target} Causal Analysis")
        lines.append("")

        ce = r.get("causal_explanation", {})
        why_high = ce.get("why_high_performance", {})
        why_low = ce.get("why_low_performance", {})
        action = ce.get("recommended_action", "")

        lines.append(f"### ✅ Why High {target}")
        lines.append(f"**Root Cause:** {why_high.get('root_cause', 'N/A')}")
        lines.append(f"")
        for d in why_high.get("details", []):
            lines.append(f"- {d}")
        lines.append(f"")

        lines.append(f"### ❌ Why Low {target}")
        lines.append(f"**Root Cause:** {why_low.get('root_cause', 'N/A')}")
        lines.append(f"")
        for d in why_low.get("details", []):
            lines.append(f"- {d}")
        lines.append(f"")

        lines.append(f"### 🔧 Recommended Action")
        lines.append(f"{action}")
        lines.append(f"")

        # Impact quantification table
        imp = r.get("impact_quantification", {}).get("top_drivers", [])
        if imp:
            lines.append(f"### 📊 Feature Impact Ranking")
            lines.append(f"| Feature | Impact | Direction |")
            lines.append(f"|---------|--------|-----------|")
            for item in imp:
                lines.append(f"| {item['feature']} | {item['impact']:+.4f} | {item['impact_label']} |")
            lines.append(f"")

        lines.append("---")
        lines.append("")

    lines.append("*Report generated by V3.6 Causal Feature Engine*")
    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════
# Internal
# ═══════════════════════════════════════════════════════════

DRIVER_EXPLANATIONS = {
    "hook_contrast": "high visual contrast in first frame → captures attention immediately → drives CTR",
    "hook_edge_density": "high edge density → visually busy/striking first frame → increases curiosity",
    "hook_entropy": "high color entropy in hook → visual richness → signals quality → increases CTR",
    "hook_saturation": "high saturation → vibrant colors → emotional arousal → higher click propensity",
    "hook_brightness": "high brightness → positive affect → brand perception uplift",
    "hook_center_contrast": "strong center subject → focal point → user knows where to look → reduces cognitive load",
    "hook_text_density": "high text density in first frame → cognitive overload → users scroll past",
    "hook_top_color_ratio": "dominant single color → brand recall → possible but risky if too uniform",
    "mid_contrast": "mid-video contrast → maintains visual interest → reduces drop-off",
    "mid_entropy": "high mid entropy → information richness → comprehension → install intent",
    "mid_text_density": "too much text mid-video → overload → comprehension drops → CVR suffers",
    "mid_saturation": "mid saturation → keeps viewer engaged → longer watch time → higher conversion",
    "mid_brightness": "mid brightness → visual clarity → easier to understand game mechanics",
    "mid_center_contrast": "mid focal point → keeps attention on key gameplay element → better understanding",
    "late_contrast": "late contrast → reward signal → satisfaction → conversion trigger",
    "late_entropy": "late entropy → payoff complexity → sufficient reward → CTA effectiveness",
    "late_saturation": "late saturation → vibrant reward → emotional payoff → install intent",
    "late_brightness": "late brightness → victory/achievement reveal → positive closure → conversion",
    "motion_contrast_delta": "contrast change → visual dynamics → maintains attention across duration",
    "motion_entropy_delta": "entropy change → content evolution → viewer stays curious → lower drop-off",
    "motion_edge_delta": "edge change → scene complexity shift → signals progression → narrative momentum",
    "motion_brightness_delta": "brightness change → mood shift → emotional journey → better narrative comprehension",
}


def _generate_high_explanation(target: str, drivers: List[Tuple[str, float]]) -> List[str]:
    """Generate why-high explanations from top drivers."""
    details = []
    for name, impact in drivers[:3]:
        explanation = DRIVER_EXPLANATIONS.get(name, f"{name} (impact {impact:+.4f})")
        pct = abs(impact) * 100
        details.append(
            f"→ {name}: +{pct:.0f}% impact on {target.upper()}. "
            f"{explanation}"
        )
    return details


def _generate_low_explanation(target: str, drivers: List[Tuple[str, float]]) -> List[str]:
    """Generate why-low explanations from negative drivers."""
    details = []
    for name, impact in drivers[:3]:
        explanation = DRIVER_EXPLANATIONS.get(name, f"{name} (impact {impact:+.4f})")
        pct = abs(impact) * 100
        if impact < 0:
            details.append(
                f"→ {name}: {pct:.0f}% negative impact on {target.upper()}. "
                f"{explanation}"
            )
    return details


def _generate_action(top_drivers: List[Tuple[str, float]],
                     negative_drivers: List[Tuple[str, float]],
                     target: str) -> str:
    """Generate single recommended action based on feature importance."""
    if top_drivers:
        top = top_drivers[0]
        action = (
            f"Increase {top[0]} by 1 standard deviation to improve {target.upper()} "
            f"by approximately {abs(top[1])*100:.0f}%."
        )
    else:
        action = f"No actionable feature identified for {target.upper()}."

    if negative_drivers:
        neg = negative_drivers[0]
        action += (
            f" Simultaneously, reduce {neg[0]} to avoid "
            f"{abs(neg[1])*100:.0f}% negative impact on {target.upper()}."
        )

    return action
